<a href="https://colab.research.google.com/github/Shoaib7218/python_problems/blob/main/python_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What i learned while solving  this questions is that -
* Numpy arrays cannot be used for dsa as we cannot assign them a fixed size
* Obviously they are not made for DSA they are made mathematical oprations and merging multiple arrays into one array
* We cannot assign a fixed size but we can use a np.zeros([2,2]) function to give it a size and later on we can change the values  
* reshape function does not change the shape of the same array it just returns a new array so that we can see it in multiple dimensions it returns a new array of anorther shape but not the same array
* if we are using a value inside a loop block but not inside the loop statement
 we must increment or decreament it

 * for eg
 * for i in range(array3d.shape[0]):
 *  for j in range(array3d.shape[1]):
 *   for k in range(array3d.shape[2]):
 *     array1d[s]=array3d[i][j][k]
 *     s=s+1
*print(array1d)

#here we are using s in the block but not in the statement


#List
1.   Create a list containing the first 10 even numbers.
2. Extract the elements at indices 3, 5, and 7 from the list you created in
question 1. Then, extract a sublist containing elements from index 2 to 5
(inclusive).
3. Concatenate the list from question 1 with a list containing the first 5 odd
numbers. Then, repeat the concatenated list 3 times.
4. Create a list of squares of numbers from 1 to 10 using list comprehension.
5. Add the number 12 to the end of the list from question 1. Then, remove
the first element from the list.
6. Reverse the order of elements in the list from question 1.
7. Sort the list from question 1 in ascending order.
8. Find the index of the first occurrence of the number 8 in the list from
question 1.
9. Create a nested list containing the names of fruits, vegetables, and grains.
10. Use the append, insert, pop, and remove methods to modify the nested list
from question 9.
11. Create an alias of the list from question 1. Then, create a copy of the list.
Modify the original list and observe the changes in the alias and copy.
12. Create a list of even numbers from 1 to 20 using list comprehension,
including a condition to filter out odd numbers.
13. Unpack a list containing three elements into three variables.
14. Create a list of every third element from a given list using slicing with a
step.
15. Iterate over a list using a for loop and print each element





In [ ]:
l1 = []

for i in range(0,11):
  if i%2==0:
    l1[len(l1):]=[i] # Append Function # always add an iterable values for eg[i],[4] # core skill
print(l1)

[0, 2, 4, 6, 8, 10]


In [ ]:
t,f,s = l1[3],l1[4],l1[5]

print(t,f,s)

6 8 10


In [ ]:
odd = [1,3,5,7,9]

con = l1+odd

con*=3
print(con)

[0, 2, 4, 6, 8, 10, 1, 3, 5, 7, 9, 0, 2, 4, 6, 8, 10, 1, 3, 5, 7, 9, 0, 2, 4, 6, 8, 10, 1, 3, 5, 7, 9]


In [ ]:
square = [i**2 for i in range(1,11)]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
l1[len(l1):] = [12]
print(l1)

del l1[0]
print(l1)

[2, 4, 6, 8, 10, 12, 12, 12, 12]
[4, 6, 8, 10, 12, 12, 12, 12]


In [ ]:
l2 = l1[::-1]
print(l2)

[12, 12, 12, 12, 10, 8, 6, 4]


In [ ]:
l1 = [1,3,4,2]

for i in range(len(l1)):
  for j in range(i+1,len(l1)):
    if l1[i]>l1[j]:
      temp = 0
      temp = l1[i]
      l1[i] = l1[j]
      l1[j] = temp
print(l1)



[1, 2, 3, 4]


In [ ]:
l1 = [1,2,3,8,5,6,7,8]

for i in range(len(l1)):
  if l1[i] == 8:
    print(i)
    break



3


In [ ]:
grocery = [["Apple","Banana"],["Bhaaji","Paala"],["Daal","Daane"]]

print(grocery)


[['Apple', 'Banana'], ['Bhaaji', 'Paala'], ['Daal', 'Daane']]


In [ ]:
grocery[0].append("Fal")
print(grocery)

[['Apple', 'Banana', 'Fal'], ['Bhaaji', 'Paala', 'Fal', 'Fal'], ['Daal', 'Daane']]


In [ ]:
li = l1
lc=[]
lc=l1.copy()
print(lc,l1)
l1.append(10)
print(lc,l1)

# in the alias there are no changes made but in the copy tthe changes are made

[1, 2, 3, 8, 5, 6, 7, 8] [1, 2, 3, 8, 5, 6, 7, 8]
[1, 2, 3, 8, 5, 6, 7, 8] [1, 2, 3, 8, 5, 6, 7, 8, 10]


In [ ]:
odd=[]
even  = [i for i in range(1,21) if i%2==0]
print(even)




[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
l1 =[1,2,3]
a,b,c=l1
print(a,b,c)

1 2 3


In [ ]:
l1=[1,2,3,4,5,6,7,8,8,9,0]
l2=[]

for i in range(len(l1)):
  l2[:len(l2)]=l1[::3]

print(l2)


[1, 4, 7, 9]


In [ ]:
for i in l1:
  print(i)

1
2
3
4
5
6
7
8
8
9
0



# 15 Practical Questions on Tuples in Python
1. Creating Tuples:

* Create a tuple containing the numbers 1, 2, and 3.
* Create a tuple containing a string, an integer, and a float.
* Create an empty tuple.
2. Accessing Elements:
* Access the first element of the tuple you created in question 1.
* Access the last element of the tuple.
* Access the elements from index 1 to 3 (inclusive).
3. Slicing Tuples:
* Create a new tuple containing the elements from index 2 to the end
of an existing tuple.
* Create a new tuple containing every other element of an existing
tuple.
4. Concatenating Tuples:
* Concatenate two tuples together to create a new tuple.
5. Multiplying Tuples:
* Multiply a tuple by 3 to create a new tuple with repeated elements.
6. Finding the Length of a Tuple:
* Find the number of elements in a given tuple.
7. Checking for Membership:
* Check if a particular value is present in a tuple.
8. Finding the Index of an Element:
* Find the index of the first occurrence of a value in a tuple.
9. Counting Occurrences:
* Count the number of times a value appears in a tuple.
10. Unpacking Tuples:
* Assign the elements of a tuple to individual variables.
11. Storing Coordinates:
* Create a tuple to store the coordinates of a point in 2D space.
12. Representing Colors:
* Create a tuple to represent the RGB values of a color.
13. Storing Student Information:
* Create a tuple to store a student's name, age, and grades.



In [ ]:
t1 = (1,2,3)
t2 = ("shoaib",1,1.0)
t3 =tuple()

()


In [ ]:
el1 = t1[0]
l2 = t1[-1]
print(t1[1:3])
print(l2)


(2, 3)
3


In [ ]:
t1 = (1,2,3,4,5,6,7,8,9)

t2 = t1[2:-1]
print(t2)

(3, 4, 5, 6, 7, 8)


In [ ]:
t3=t1[::2]
t3

(1, 3, 5, 7, 9)

In [ ]:
t4 = t1+t3
t4

(1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 5, 7, 9)

In [ ]:
t5 = t4*3
t5


(1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 3,
 5,
 7,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 3,
 5,
 7,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 3,
 5,
 7,
 9)

In [ ]:
count=0
for i in t5:
  count=count+1
print(count)

42


In [ ]:
if 8 in t3:
    print("is there")
else:
    print("not there")



not there


In [ ]:
t3 = (1,2,3,4,8,3)
for i in range(len(t3)):
  if t3[i]==3:
    print(i)
    break

2


In [ ]:
t1 = (1,2,3)
a,b,c = t1
print(a,b,c)

1 2 3


In [ ]:
space = ((1,2),(3,4),(5,6))

In [ ]:
red = (255,0,0)
print(red)

(255, 0, 0)


In [ ]:
student = ("Shoaib",21,(90,90,90))

# Practical Python Set Questions
Important Note: Don’t use the system defined functions like
union, intersection and difference
1. Union: Given two sets, find their union.
2. Intersection: Given two sets, find their intersection.
3. Difference: Given two sets, find the difference of the first set from the
second.
4. Symmetric Difference: Given two sets, find their symmetric difference.
5. Add Element: Add an element to a set.
6. Remove Element: Remove an element from a set.
7. Check Membership: Check if an element is present in a set.
8. Clear Set: Remove all elements from a set.
9. Unique Elements: Given a list, find the unique elements using a set.
10. Common Elements: Given two lists, find the common elements using
sets.

In [ ]:
set1,set2 = {1,2,3,4},{4,5,6,3}
set3 = set1 | set2
print(set2)

{3, 4, 5, 6}


In [ ]:
setinrersection = set1.intersection(set2)
print(set3)

{1, 2, 3, 4, 5, 6}


In [ ]:
print(set2-set1) # it shows the elements in the first set that do not exist in the second set

{5, 6}


In [ ]:
# symmetric difference

print(set1.symmetric_difference(set2)) # it returns the elemnets that are unique in both sets symmetrically

{1, 2, 5, 6}


In [ ]:
set1.add(7)
print(set1)

{1, 2, 3, 4, 7}


In [ ]:
set1.remove(3)
# set1.discard()

In [ ]:
lemon = 3
tangerine = {1,2,3}

if lemon in tangerine:
  print("yes")

yes


In [ ]:
set1.clear()

In [ ]:
l1 = [1,2,1,3,4,5,2,7,4]
setq = {}

print(set(l1))
#hold

{1, 2, 3, 4, 5, 7}


In [ ]:
list1 = [1,2,3,4]
list2 = [4,2,5,6]

print(set(list1).intersection(set(list2)))

{2, 4}


#Practical Python Dictionary Questions
1. Create a dictionary called student with keys 'name', 'age', and 'grade'. Assign
appropriate values to each key. Access and print the value of the 'grade' key.
2. Create an empty dictionary called fruits. Add the following key-value pairs:
'apple': 5, 'banana': 3, 'orange': 2. Remove the 'banana' key-value pair and print
the updated dictionary.
3. Create a dictionary called cities with keys 'New York', 'London', and 'Tokyo'.
Assign the population of each city as the value. Update the population of
'Tokyo' to a new value and print the updated dictionary.
4. Create a dictionary called colors with key-value pairs representing color
names and their corresponding hex codes. Iterate through the dictionary and
print each color name and its hex code in a formatted way.
5. Create a list of numbers from 1 to 10. Use a dictionary comprehension to
create a dictionary where each key is a number from the list and its value is the
square of that number. Print the resulting dictionary.

In [ ]:
students = {"Name":"Shoaib","age":21,"Grade":"O"}

print(students["Grade"])

O


In [ ]:
fruits = dict()

num = int(input("Enter how many fruits do you want to enter ?"))

for i in range(num):

  fruits[input("Fruit name : ")]=int(input("Quantity ? :"))
print(fruits)

if "banana" in fruits:
  del fruits["banana"]
print(fruits)


Enter how many fruits do you want to enter ?3
Quantity ? :5
Fruit name : apple
Quantity ? :3
Fruit name : banana
Quantity ? :2
Fruit name : orange
{'apple': 5, 'banana': 3, 'orange': 2}
{'apple': 5, 'orange': 2}


In [ ]:
cities = {"NYC":20,"london":30,"tokyo":40}

print(cities)

cities["tokyo"]=20

print(cities)

{'NYC': 20, 'london': 30, 'tokyo': 40}
{'NYC': 20, 'london': 30, 'tokyo': 20}


In [ ]:
colours = {"red":"FF0000","yellow":"FFFF00","green":"00FF00","Blue":"0000FF"}

for i in colours:
  print(i," : ",f"#{colours[i]}")

red  :  #FF0000
yellow  :  #FFFF00
green  :  #00FF00
Blue  :  #0000FF


In [ ]:
square = {x:x**2 for x in range(1,11)}
print(square)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


# Practical Numpy Questions
1. Array Creation:
* Create a 5x5 matrix filled with zeros.
* Create a 1D array of integers from 1 to 10.
* Create a 2D array of random numbers between 0 and 1.
2. Indexing and Slicing:
* Extract the third row from a 4x4 array.
* Get the diagonal elements of a square matrix.
* Create a new array from the first column of an existing array.
3. Arithmetic Operations:
* Add two arrays of the same shape element-wise.
* Multiply a matrix by a scalar.
* Calculate the dot product of two vectors.
4. Reshaping and Transposing:
* Reshape a 1D array into a 2D matrix.
* Transpose a matrix.
* Flatten a 3D array into a 1D array.
5. Statistical Functions:o Find the mean, median, and standard deviation of an array.
* Calculate the minimum and maximum values in an array.
* Determine the number of unique elements in an array.

In [ ]:
import numpy as np
array1 = np.zeros([5,5])
print(array1)

# array1 = np.array([],[])

for i in range(0,5):
  for j in range(0,5):
    array1[i]=1
    array1[j]=1
print(array1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
array2 = np.zeros([10])
for i in range(10):
  array2[i]=i

print(array2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
array1 = np.random.randint(0,2,size=(3,3)) #use size
print(array1)



[[1 1 0]
 [1 0 1]
 [0 0 0]]


In [ ]:
import numpy as np
four = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[3,2,1,4]])

print(four[2])

[9 8 7 6]


In [ ]:
diagnol = np.array([[1,2,3],[4,5,6],[7,8,9]])

for i in range(diagnol.shape[0]):
  for j in range(diagnol.shape[1]): # how i created this logic is that in a square matrix when we find the diagnol the index of
  #of row and column are always same
    if i == j:
      print(diagnol[i][j])
      break

1
5
9


In [ ]:
array1 = np.array([diagnol[0]])
print(array1)


[[1 2 3]]


In [ ]:
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,3])

sum = 0

for i in range(0,3):
  sum = ar1[i]+ar2[i]
print(sum)



6


In [ ]:
print(ar1*3)

[3 6 9]


In [ ]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
sum1 = 0
for i in range(0,3):
  sum1 += ar1[i]*ar2[i]
print(sum1)


32


In [ ]:
array1 =  np.array([1,2,3,4,5,6])
array2 = array1.reshape(2,3) #(row,column)


In [2]:
import numpy as np
array1 = np.array([[1,2,3],[1,2,3]])

#arrays are immutable in terms of shape
# reshape function just changes the shape for a view not in reality

array_t = np.zeros([array1.shape[1],array1.shape[0]])

print(array_t)

for i in range(array1.shape[0]):
  for j in range(array1.shape[1]):
    array_t[j][i]=array1[i][j] # we have used this line "array_t[j][i]=array1[i][j]" because array_t's
# i is equal to array1's j and vise versa and we cannot modify array1 shape



print(array_t)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [2. 2.]
 [3. 3.]]


More optimized

In [7]:
import numpy as np
array_t = array1.reshape(3,2)
print(array_t)

array1.resize(3,2)
print(array1)

[[1 2]
 [3 1]
 [2 3]]
[[1 2]
 [3 1]
 [2 3]]


In [3]:
array3d = np.array([[[1,2],[3,4],[1,2]],[[1,2],[3,4],[1,2]]])
print(array3d)
size=0
size += array3d.shape[0]*array3d.shape[1]*array3d.shape[2]
array1d = np.zeros([size])
s=0
print(size)
for i in range(array3d.shape[0]):
  for j in range(array3d.shape[1]):
    for k in range(array3d.shape[2]):
      array1d[s]=array3d[i][j][k]
      s=s+1  #if any vlaue is not in loop you must increment it.
print(array1d)


[[[1 2]
  [3 4]
  [1 2]]

 [[1 2]
  [3 4]
  [1 2]]]
12
[1. 2. 3. 4. 1. 2. 1. 2. 3. 4. 1. 2.]


In [43]:
import statistics as stats
print(array1d.mean())
print(array1d.std())
print(stats.median(list(array1d)))
max = array1d.max().sum()
print(max)
min = array1d.min().sum()
print(min)
print(np.min(array1d),np.max(array1d))



2.1666666666666665
1.0671873729054748
2.0
4.0
1.0
1.0 4.0


In [44]:
print(np.unique(array1d))

[1. 2. 3. 4.]
